server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

  resilience4j:
    circuitbreaker:
      instances:
        movies:  #Este nombre debe coincidir con el que se encuentra en el programa en "name"
          slidingWindowType: COUNT_BASED  #Hay dos tipos por ventanas de tiempo o de eventos
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 15000
          permittedNumberOfCallsInHalfOpenState: 3
          registerHealthIndicator: true
          allowHealthIndicatorToFail: false
          automaticTransitionFromOpenToHalfOpenEnabled: true
