eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        #registry-fetch-interval-seconds: 5
        healthchecks:
            enabled: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
    server:
        wait-time-in-ms-when-sync-empty: 0

spring:
  zipkin:
    base-url: http://192.168.99.100:9411/
    enabled: true
