eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        registry-fetch-interval-seconds: 5
        healthchecks:
            enabled: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true

server:
    port: 80

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: movieRoute
                  uri: lb://movie-service/
                  predicates:
                      - Path=/api/v1/movies/**
                  filters:
                      - StripPrefix=2
