server:
    port: 8080

spring:
    application:
        name: gateway-service
    zipkin:
        base-url: http://192.168.99.100:9411/
        enabled: true
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: catalogRoute
                  uri: lb://catalog-service/
                  predicates:
                      - Path=/catalog/**
            #default-filters:
                #- name: FilterCustom

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 5
        healthchecks:
            enabled: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  #Para ver multiples instancias en Eureka
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
